//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "answers")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    #[serde(skip_deserializing)]
    pub id: Uuid,
    pub question_id: Uuid,
    pub value: String,
    pub is_correct: bool,
    pub lang: String,
    #[sea_orm(
        belongs_to,
        from = "question_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub questions: HasOne<super::questions::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
