//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "lessons")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    #[serde(skip_deserializing)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub topic_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub content: String,
    #[sea_orm(
        belongs_to,
        from = "topic_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub topics: HasOne<super::topics::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
