//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "questions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    #[serde(skip_deserializing)]
    pub id: Uuid,
    pub topic_id: Uuid,
    pub name: String,
    pub lang: String,
    #[sea_orm(has_many)]
    pub answers: HasMany<super::answers::Entity>,
    #[sea_orm(
        belongs_to,
        from = "topic_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub topics: HasOne<super::topics::Entity>,
    #[sea_orm(has_many, via = "user_favorite_questions")]
    pub users: HasMany<super::users::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
