//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "tests")]
pub struct Model {
    #[sea_orm(column_name = "_created_at")]
    #[serde(skip)]
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(column_name = "_updated_at")]
    #[serde(skip)]
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(column_name = "_is_active")]
    #[serde(skip)]
    pub is_active: bool,
    #[sea_orm(column_name = "_is_deleted")]
    #[serde(skip)]
    pub is_deleted: bool,
    #[sea_orm(primary_key, auto_increment = false)]
    #[serde(skip_deserializing)]
    pub id: Uuid,
    #[sea_orm(unique_key = "idx_tests_user_filter_hash_active")]
    pub user_id: Uuid,
    pub filter_type: String,
    pub filter_id: Option<Uuid>,
    pub lang: String,
    #[sea_orm(unique_key = "idx_tests_user_filter_hash_active")]
    pub filter_hash: String,
    pub total_questions: i16,
    pub correct_count: i16,
    pub status: String,
    pub score_percent: Option<i16>,
    pub completed_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(has_many)]
    pub test_question_answers: HasMany<super::test_question_answers::Entity>,
    #[sea_orm(
        belongs_to,
        from = "user_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub users: HasOne<super::users::Entity>,
    #[sea_orm(has_many, via = "test_questions")]
    pub questions: HasMany<super::questions::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
