//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "test_questions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    #[serde(skip_deserializing)]
    pub test_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    #[serde(skip_deserializing)]
    pub question_id: Uuid,
    pub question_order: i16,
    pub is_correct: Option<bool>,
    pub answered_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(
        belongs_to,
        from = "question_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub questions: HasOne<super::questions::Entity>,
    #[sea_orm(
        belongs_to,
        from = "test_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub tests: HasOne<super::tests::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
