//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "topics")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    #[serde(skip_deserializing)]
    pub id: Uuid,
    pub name: String,
    pub difficulty: String,
    pub duration: i16,
    pub subscription_required: bool,
    #[sea_orm(has_one)]
    pub lessons: HasOne<super::lessons::Entity>,
    #[sea_orm(has_many)]
    pub questions: HasMany<super::questions::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
