//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "user_subscriptions")]
pub struct Model {
    #[sea_orm(column_name = "_created_at")]
    #[serde(skip)]
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(column_name = "_updated_at")]
    #[serde(skip)]
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(column_name = "_is_active")]
    #[serde(skip)]
    pub is_active: bool,
    #[sea_orm(column_name = "_is_deleted")]
    #[serde(skip)]
    pub is_deleted: bool,
    #[sea_orm(primary_key, auto_increment = false)]
    #[serde(skip_deserializing)]
    pub id: Uuid,
    pub user_id: Uuid,
    pub expire_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub users: HasOne<super::users::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
